### ISSUE TITLE
cvc complex field

### ISSUE THREAD

**Issue by marcuspetschlies** [NikSchlage/cvc-ns#3]
the output field for co_field_eq_fv_dag_ti_gamma_ti_fv must be a complex field; the type is defined in
cvc_complex.h

That function is a 4-volume-wide application of _co_eq_fv_dag_ti_fv, which is defined in cvc_linalg.h,

complex * myname = (complex*) malloc (  VOLUME * sizeof ( complex ) );

Actually, there is no real need to store the field per point for all points; we only need the sum over 4-volume.

Alternatively, use spinor_field_eq_gamma_ti_spinor_field (in cvc_utils)  and a scalar product, which automatically reduces 
over 4-volume.

**Comment by NikSchlage** [comment]
The calculation of Z_chi is now implemented. For this I have defined a new function _co_eq_re_by_co, see cvc_complex.h.
