### ISSUE TITLE
GF step size

### ISSUE THREAD

**Issue by marcuspetschlies** [NikSchlage/cvc-ns#6]
flow_fwd_gauge_spinor_field should not necessarily be called with gf_dt and 1 iteration; gf_dt should be  the "small" discretization step of flow time;

A measurement would not be taken after each iteration.

**Comment by NikSchlage** [comment]
Now I generally pass gf_niter to the function flow_fwd_gauge_spinor_field instead of exclusively setting gf_niter = 1.
