### ISSUE TITLE
scalar product

### ISSUE THREAD

**Issue by marcuspetschlies** [NikSchlage/cvc-ns#7]
spinor_scalar_product_co produces a single number of complex type; there is no need for fields
zchi/_aux/... ; 

spinor_scalar_product_co reduces over all volume (and all spin-color degrees of freedom ).

**Comment by NikSchlage** [comment]
Thanks, I had overlooked removing the multiplication with VOLUME within malloc.

**Comment by marcuspetschlies** [comment]
no need for malloc, really; simple variable will do

**Comment by NikSchlage** [comment]
Yes, I've changed the initialization of the complex numbers accordingly.
