### ISSUE TITLE
repeated flow calls

### ISSUE THREAD

**Issue by marcuspetschlies** [NikSchlage/cvc-ns#8]
flow_fwd_gauge_spinor_field ( gauge_field_smeared, spinor_field_1[0][isample], 1, gf_dt, 1, 1 ); 
...    
flow_fwd_gauge_spinor_field ( gauge_field_smeared, spinor_field_1[1][isample], 1, gf_dt, 1, 1 );

This will not work correctly; the GF if gauge_field_smeared is continued by repeated calls

The second call to flow_fwd_gauge_spinor_field would start already with the flowed gauge field

1) either reset gauge field before the 2nd call
2) or add functionality flow_fwd_gauge_spinor_field to allow flowing several fields

**Comment by NikSchlage** [comment]
Now the gauge field is reset before the next call.

**Comment by NikSchlage** [comment]
I've now fixed the reset problem and reset the gauge field before the 2nd call of flow_fwd_gauge_spinor_field using a copy of the initial gauge_field_smeared called gauge_field_smeared_2.
